### PR TITLE
#12-fix-prisma-client-generation-issue-on-vercel

### PR DESCRIPTION
**Pull request by bazmurphy**
This is a:

- [ ] ✨ **New feature** - new behaviour has been implemented
- [X] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

- **Purpose** - 
At the moment Vercel uses a cached version of dependencies which means we do not get a new Prisma Client generated each time.
We want to make sure the Prisma Client is "generated" each time the build runs on Vercel (which happens automatically after any changes to this repository). 
And in that way the project should deploy successfully.

- **How to check** - 
In theory we could add this postinstall command on the Vercel UI, but that would defeat the purpose of this PR. 
And it would be an extra step to remember - in this way it is contained within the code.
I think the only way to check this works is to merge this PR and observe the build log on Vercel.

### Links
- Story: #12  

### Author checklist

- [X] I have written a title that reflects the relevant ticket
- [X] I have written a description that says what the PR does and how to validate it
- [X] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [X] I have added a link to this PR to the ticket
- [X] I have requested reviewers here and in my team chat channel

### CODE REVIEW

**Comment by susanssky** [comment]
So, I have asked if we need to create a `production` branch for `backup`, and a `main` branch to test this work and verify if it works.

**Comment by bazmurphy** [comment]
> So, I have asked if we need to create a `production` branch for `backup`, and a `main` branch to test this work and verify if it works.

Usually `production` or `main` are the final step.
So we could make `development` and `main` (or `production` if you want to call it that)

development > main/production

**Comment by bazmurphy** [comment]
image

I would like to remove this^ and have it exist in the `package.json` as instructed from the Prisma documentation which I wrote about here : https://github.com/leilafarsani/To-Do-List-Group-Work/issues/12 
And that references here: https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/vercel-caching-issue

**Review by susanssky — APPROVED** [review]
OK :(

**Comment by bazmurphy** [comment]
It is the method recommended by Prisma: "This is the preferred method as it is a universal solution."

If everything is OK here could you approve it and merge it please.

**Pull request merged**
